name: 'yeswiki-build-repo'
description: 'Build script to package [YesWiki] **extensions** and **themes**.'
inputs:
  extension-dir:
    description: 'Extension directory to test and package.'
    required: true
    default: ${{ github.workspace }}
  output-dir:
    description: 'Path to extract shasum and zipped archive to.'
    required: false
    default: /tmp
  extension-name:
    description: 'Path to extract shasum and zipped archive to.'
    required: false
    default: ${{ github.repository }}
  extension-version:
    description: 'Path to extract shasum and zipped archive to.'
    required: false
    default: ${{ github.ref.replace('/refs/tags/', '') }}
outputs:
  md5sum:
    description: 'Package integrity signature.'
  md5sum:
    description: 'Package integrity signature.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.extension-dir }}
    - ${{ inputs.output-dir }}
    - ${{ inputs.extension-name }}
    - ${{ inputs.extension-version }}
