name: 'yeswiki-build-repo'
description: 'Build script to package [YesWiki] **extensions** and **themes**.'
branding:
  icon: 'package'
  color: 'yellow'
inputs:
  extension-dir:
    description: 'Extension directory to test and package.'
    required: true
    default: /github/workspace
  output-dir:
    description: 'Path to extract shasum and zipped archive to.'
    required: false
    default: /dist
  extension-name:
    description: 'YesWiki extension name (eg: yeswiki-extension-publication)'
    required: false
  extension-version:
    description: 'YesWiki extension version (eg: 2020-06-12)'
    required: false
outputs:
  md5sum:
    description: 'Package integrity signature.'
  archive-name:
    description: 'Package integrity signature.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.extension-dir }}
    - ${{ inputs.output-dir }}
    - ${{ inputs.extension-name }}
    - ${{ inputs.extension-version }}
