on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test this Action
    steps:
    - uses: actions/checkout@v2

    - name: Self-test
      run: |
        composer install
        composer test

    - name: Package a dummy extension
      uses: ./
      id: package
      with:
        extension-dir: /github/workspace/yeswiki-extension-test

    - name: Get the test extension md5sum
      run: echo "md5sum is ${{ steps.package.outputs.md5sum }}"
    - name: Get the test extension archive-name
      run: echo "archive-name is ${{ steps.package.outputs.archive-name }}"

  docker-release:
    runs-on: ubuntu-latest
    steps:
    - name: Build and push
      uses: jerray/publish-docker-action@v1.0.5
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GCR_PAT }}
        repository: oncletom/yeswiki-build-repo
        auto_tag: true
        file: ./Dockerfile
        path: .
